version: '3.7'

services:
  cache:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_gtfseditor_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/docker_db_env
    ports:
      - "5432:5432"

volumes:
  postgres_gtfseditor_data:
